name: CI

on: [pull_request]

jobs:
  run_all_tests:
    name: Run all tests
    uses: cpp-for-yourself/ci-jobs/.github/workflows/check-homework.yml@main
    with:
      homework-definitions-branch: main
permissions:
  contents: write
  issues: write
  pull-requests: write